[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdl"
version = "0.1.0"
description = "Brutally simple, lighting fast Patreon downloader"
authors = [{name = "hornysde", email = "hornysde@proton.me"}]
license = {file = "LICENSE"}
requires-python = ">=3.11"

dependencies = [
    "aiohttp",
    "pydantic",
    "pyffmpeg",
    "tenacity",
    "tqdm",
    "yt-dlp",
]

[project.optional-dependencies]
dev = [
    "pip-tools",
    "ruff",
    "mypy",
    "types-tqdm",
]

[tool.setuptools]
py-modules = ["pdl"]

[project.scripts]
pdl = "pdl:main"

[tool.mypy]
check_untyped_defs = true
